# Generated by Django 5.0.6 on 2024-05-21 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('bName', models.CharField(max_length=50)),
                ('publisher', models.CharField(max_length=30)),
                ('author', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('edition', models.IntegerField()),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('uName', models.CharField(max_length=40)),
                ('pword', models.CharField(max_length=20)),
                ('uType', models.IntegerField(default=4)),
                ('numOfBook', models.IntegerField(default=0)),
                ('listOfBook', models.CharField(blank=True, max_length=40)),
                ('status', models.IntegerField(default=2)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('trans_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('issueDtTm', models.DateTimeField()),
                ('returnDtTm', models.DateTimeField()),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.book')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='IssuedBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trans_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.transaction')),
            ],
        ),
    ]
