# Generated by Django 5.0.6 on 2024-05-21 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='book',
            constraint=models.CheckConstraint(check=models.Q(('count__gte', 0)), name='qty_check'),
        ),
    ]
