# Generated by Django 3.2.21 on 2024-05-26 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_book_qty_check'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='returnDtTm',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
