# Generated by Django 3.2.21 on 2024-05-26 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_transaction_returndttm'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuedbook',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.user'),
        ),
    ]
